# Hugging Face Transformers 庫快速上手

本 Notebook 將全面示範如何使用 Hugging Face Transformers 庫，包括：

## 📚 內容概覽

### 基礎篇
1. **安裝與環境設定**
2. **Pipeline API 快速入門**
   - 情感分析
   - 語音識別
   - 命名實體識別 (NER)
   - 問答系統
   - 文本摘要
   - 翻譯
   - 零樣本分類

### 進階篇
3. **模型與分詞器詳解**
   - AutoModel 和 AutoTokenizer 使用
   - 批次處理技巧
   - 多語言支援
4. **模型推理與優化**
   - 手動推理流程
   - GPU/CPU 配置
   - 批次推理優化
5. **模型訓練與微調**
   - 使用 Trainer API
   - 自定義訓練循環
   - 模型評估與指標
6. **最佳實踐**
   - 錯誤處理
   - 記憶體管理
   - 性能優化

---

**環境需求**：
- Python 3.7+
- PyTorch 或 TensorFlow
- CUDA (可選，用於 GPU 加速)

**預計時間**：30-60 分鐘

1. 安裝必要套件
在 Colab 的第一個程式碼區塊中，請先安裝 transformers、datasets、evaluate 與 accelerate，另外根據你使用的框架選擇安裝 PyTorch 或 TensorFlow（可依需求同時安裝兩者）。

In [1]:
!pip install transformers datasets evaluate accelerate
!pip install torch         # 若要使用 PyTorch
!pip install tensorflow    # 若要使用 TensorFlow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 14.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 14.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 16.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 87.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 76.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 51.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 37.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

2. 使用 pipeline 進行情感分析
以下範例展示如何使用 pipeline 快速執行情感分析任務。

In [2]:
from transformers import pipeline

# 建立情感分析的 pipeline（會自動下載預訓練模型與分詞器）
classifier = pipeline("sentiment-analysis")

# 單筆輸入範例
result = classifier("We are very happy to show you the Transformers library.")
print(result)

# 多筆輸入範例
results = classifier([
    "We are very happy to show you the Transformers library.",
    "We hope you don't hate it."
])
for res in results:
    print(f"label: {res['label']}, score: {round(res['score'], 4)}")


No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Device set to use cuda:0


[{'label': 'POSITIVE', 'score': 0.9997994303703308}]
label: POSITIVE, score: 0.9998
label: NEGATIVE, score: 0.5309


3. 使用 Speech Recognition Pipeline 搭配資料集
此範例示範如何利用語音識別 pipeline 搭配 Hugging Face Datasets 讀取音頻資料並執行推理。

In [3]:
import torch
from transformers import pipeline
from datasets import load_dataset, Audio

# 建立語音識別 pipeline，使用 facebook/wav2vec2-base-960h 模型
speech_recognizer = pipeline("automatic-speech-recognition", model="facebook/wav2vec2-base-960h")

# 載入 PolyAI/minds14 音頻資料集 (此處選用 "en-US" 分割)
dataset = load_dataset("PolyAI/minds14", name="en-US", split="train")

# 將資料集中的 audio 欄位轉型以符合模型所需的採樣率
dataset = dataset.cast_column("audio", Audio(sampling_rate=speech_recognizer.feature_extractor.sampling_rate))

# 對前 4 筆音頻資料執行推理
result = speech_recognizer(dataset[:4]["audio"])
print([d["text"] for d in result])


config.json:   0%|          | 0.00/1.60k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/159 [00:00<?, ?B/s]

Device set to use cuda:0


README.md:   0%|          | 0.00/5.28k [00:00<?, ?B/s]

minds14.py:   0%|          | 0.00/5.83k [00:00<?, ?B/s]

The repository for PolyAI/minds14 contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/PolyAI/minds14.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y


MInDS-14.zip:   0%|          | 0.00/471M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

['I WOULD LIKE TO SET UP A JOINT ACCOUNT WITH MY PARTNER HOW DO I PROCEED WITH DOING THAT', "FONDERING HOW I'D SET UP A JOIN TO HELL T WITH MY WIFE AND WHERE THE AP MIGHT BE", "I I'D LIKE TOY SET UP A JOINT ACCOUNT WITH MY PARTNER I'M NOT SEEING THE OPTION TO DO IT ON THE APSO I CALLED IN TO GET SOME HELP CAN I JUST DO IT OVER THE PHONE WITH YOU AND GIVE YOU THE INFORMATION OR SHOULD I DO IT IN THE AP AN I'M MISSING SOMETHING UQUETTE HAD PREFERRED TO JUST DO IT OVER THE PHONE OF POSSIBLE THINGS", 'HOW DO I FURN A JOINA COUT']


In [ ]:
from transformers import pipeline

# 建立零樣本分類 pipeline
zero_shot_classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

# 待分類文本
text = "I love using Transformers library. It makes NLP so easy!"

# 候選標籤
candidate_labels = ["technology", "sports", "politics", "entertainment", "education"]

# 執行分類
result = zero_shot_classifier(text, candidate_labels)

print(f"文本: {text}\n")
print("分類結果：")
for label, score in zip(result['labels'], result['scores']):
    print(f"  {label}: {score:.4f}")

print("\n" + "="*50 + "\n")

# 多標籤分類示例
text2 = "This new programming course teaches Python and machine learning concepts."
candidate_labels2 = ["education", "technology", "business", "health"]

result2 = zero_shot_classifier(text2, candidate_labels2, multi_label=True)

print(f"文本: {text2}\n")
print("多標籤分類結果：")
for label, score in zip(result2['labels'], result2['scores']):
    print(f"  {label}: {score:.4f}")

## 2.6 零樣本分類 (Zero-shot Classification)

零樣本分類可以在沒有訓練數據的情況下對文本進行分類。

In [ ]:
from transformers import pipeline

# 英文翻譯成德文
en_to_de = pipeline("translation_en_to_de", model="Helsinki-NLP/opus-mt-en-de")

text_en = "Hugging Face is creating a tool that democratizes AI."
result = en_to_de(text_en)
print(f"英文: {text_en}")
print(f"德文: {result[0]['translation_text']}")

print("\n" + "="*50 + "\n")

# 英文翻譯成法文
en_to_fr = pipeline("translation_en_to_fr", model="Helsinki-NLP/opus-mt-en-fr")

texts = [
    "Machine learning is a subset of artificial intelligence.",
    "Deep learning models require large amounts of data."
]

print("批次翻譯（英文 -> 法文）：")
for text in texts:
    result = en_to_fr(text)
    print(f"  EN: {text}")
    print(f"  FR: {result[0]['translation_text']}\n")

## 2.5 機器翻譯 (Translation)

使用預訓練的翻譯模型進行語言翻譯。

In [ ]:
from transformers import pipeline

# 建立摘要 pipeline
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

# 長文本範例
article = """
Artificial intelligence (AI) is intelligence demonstrated by machines, in contrast to the natural 
intelligence displayed by humans and animals. Leading AI textbooks define the field as the study 
of "intelligent agents": any device that perceives its environment and takes actions that maximize 
its chance of successfully achieving its goals. Colloquially, the term "artificial intelligence" 
is often used to describe machines (or computers) that mimic "cognitive" functions that humans 
associate with the human mind, such as "learning" and "problem solving".

As machines become increasingly capable, tasks considered to require "intelligence" are often 
removed from the definition of AI, a phenomenon known as the AI effect. A quip in Tesler's Theorem 
says "AI is whatever hasn't been done yet." For instance, optical character recognition is frequently 
excluded from things considered to be AI, having become a routine technology.

Modern machine learning approaches, which include deep learning, are particularly effective for 
natural language processing, computer vision, speech recognition, and many other applications.
"""

# 生成摘要
summary = summarizer(article, max_length=100, min_length=30, do_sample=False)

print("原文長度:", len(article.split()))
print("\n摘要:")
print(summary[0]['summary_text'])
print("\n摘要長度:", len(summary[0]['summary_text'].split()))

## 2.4 文本摘要 (Summarization)

文本摘要可以將長文本濃縮成簡短的摘要。

In [ ]:
from transformers import pipeline

# 建立問答 pipeline
qa_pipeline = pipeline("question-answering")

# 準備上下文和問題
context = """
The Transformer architecture was introduced in the paper "Attention is All You Need" by Vaswani et al. in 2017.
It revolutionized natural language processing by relying entirely on attention mechanisms, 
dispensing with recurrence and convolutions entirely. The model achieves state-of-the-art results 
on machine translation and other NLP tasks.
"""

# 提出多個問題
questions = [
    "Who introduced the Transformer architecture?",
    "When was the Transformer introduced?",
    "What makes the Transformer special?"
]

print("問答系統示範：\n")
for question in questions:
    result = qa_pipeline(question=question, context=context)
    print(f"Q: {question}")
    print(f"A: {result['answer']} (信心度: {result['score']:.4f})")
    print(f"   位置: {result['start']}-{result['end']}\n")

## 2.3 問答系統 (Question Answering)

問答系統可以從給定的上下文中回答問題。

In [ ]:
from transformers import pipeline

# 建立 NER pipeline
ner_pipeline = pipeline("ner", model="dslim/bert-base-NER", aggregation_strategy="simple")

# 示例文本
text = "Apple Inc. was founded by Steve Jobs in Cupertino, California."

# 執行 NER
entities = ner_pipeline(text)

print("識別出的實體：")
for entity in entities:
    print(f"  - {entity['word']}: {entity['entity_group']} (信心度: {entity['score']:.4f})")

# 中文 NER 範例（使用中文模型）
# 註：以下使用英文模型示範，實際應用可選擇中文 NER 模型
print("\n另一個範例：")
text2 = "Microsoft was founded by Bill Gates and Paul Allen in Seattle."
entities2 = ner_pipeline(text2)
for entity in entities2:
    print(f"  - {entity['word']}: {entity['entity_group']} (信心度: {entity['score']:.4f})")

## 2.2 命名實體識別 (NER)

Named Entity Recognition (NER) 用於識別文本中的實體，如人名、地名、組織名等。

4. 使用 AutoTokenizer 與 AutoModel 進行多語言情感分析
以下範例示範如何利用 AutoTokenizer 與 AutoModelForSequenceClassification 載入多語言模型，並建立一個 pipeline 處理法文文本。

In [4]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

model_name = "nlptown/bert-base-multilingual-uncased-sentiment"

# 載入模型與分詞器
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

# 建立情感分析 pipeline，指定模型與分詞器
classifier = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

# 使用法文文本進行情感預測
print(classifier("Nous sommes très heureux de vous présenter la bibliothèque Transformers."))


config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/669M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cuda:0


[{'label': '5 stars', 'score': 0.7236301302909851}]


5. 分詞器使用示例
展示如何使用分詞器對文本進行編碼，並進行批次處理（分別提供 PyTorch 與 TensorFlow 版本）。

單筆文本編碼

In [5]:
encoding = tokenizer("We are very happy to show you the Transformers library.")
print(encoding)

{'input_ids': [101, 11312, 10320, 12495, 19308, 10114, 11391, 10855, 10103, 58263, 13299, 119, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


批次處理 - PyTorch 版本

In [6]:
pt_batch = tokenizer(
    ["We are very happy to show you the Transformers library.", "We hope you don't hate it."],
    padding=True,
    truncation=True,
    max_length=512,
    return_tensors="pt",
)
print(pt_batch)


{'input_ids': tensor([[  101, 11312, 10320, 12495, 19308, 10114, 11391, 10855, 10103, 58263,
         13299,   119,   102],
        [  101, 11312, 18763, 10855, 11530,   112,   162, 39487, 10197,   119,
           102,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])}


批次處理 - TensorFlow 版本

In [7]:
tf_batch = tokenizer(
    ["We are very happy to show you the Transformers library.", "We hope you don't hate it."],
    padding=True,
    truncation=True,
    max_length=512,
    return_tensors="tf",
)
print(tf_batch)


{'input_ids': <tf.Tensor: shape=(2, 13), dtype=int32, numpy=
array([[  101, 11312, 10320, 12495, 19308, 10114, 11391, 10855, 10103,
        58263, 13299,   119,   102],
       [  101, 11312, 18763, 10855, 11530,   112,   162, 39487, 10197,
          119,   102,     0,     0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 13), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 13), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]], dtype=int32)>}


## 14. 總結與下一步

### 🎉 恭喜！你已經學會了：

#### 基礎技能
- ✅ 使用 Pipeline API 快速實現各種 NLP 任務
- ✅ 載入和使用預訓練模型
- ✅ 理解分詞器的工作原理
- ✅ 執行模型推理和預測

#### 進階技能
- ✅ 微調模型以適應特定任務
- ✅ 使用 Trainer API 進行模型訓練
- ✅ 評估模型性能並使用各種指標
- ✅ 視覺化模型結果
- ✅ 實現錯誤處理和最佳實踐
- ✅ 優化 GPU/CPU 使用和推理性能

---

### 📚 推薦學習資源

1. **官方文檔**
   - [Transformers 文檔](https://huggingface.co/docs/transformers/)
   - [Hugging Face Course](https://huggingface.co/course)
   
2. **實踐項目**
   - 瀏覽 [Hugging Face Hub](https://huggingface.co/models) 上的模型
   - 嘗試 [Spaces](https://huggingface.co/spaces) 上的演示應用
   
3. **社群資源**
   - [Hugging Face 論壇](https://discuss.huggingface.co)
   - [Discord 社群](https://discord.gg/hugging-face)

---

### 🚀 下一步建議

#### 如果你想深入學習：
1. **探索更多模型類型**
   - 大語言模型 (LLaMA, Mistral, GPT)
   - 視覺模型 (ViT, CLIP, DETR)
   - 多模態模型 (BLIP, Flamingo)

2. **學習進階技術**
   - LoRA 和 PEFT 高效微調
   - 使用 Accelerate 進行分布式訓練
   - 模型部署和優化 (ONNX, TensorRT)

3. **參與開源項目**
   - 在 Hub 上分享你的模型
   - 為 Transformers 貢獻代碼
   - 創建自己的 Spaces 應用

---

### 💡 實踐建議

```python
# 開始你的第一個項目！
# 1. 選擇一個感興趣的任務
# 2. 找到合適的預訓練模型
# 3. 在你的數據上微調
# 4. 評估和優化
# 5. 部署和分享
```

---

**記住**：最好的學習方式就是動手實踐。選擇一個項目，開始編碼，遇到問題就查閱文檔或尋求社群幫助！

祝你在 NLP 和 AI 的學習旅程中取得成功！🎊

In [ ]:
import torch
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

# 1. 檢查 GPU 可用性
print("=== 1. GPU 配置檢查 ===\n")

print(f"CUDA 是否可用: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA 版本: {torch.version.cuda}")
    print(f"GPU 數量: {torch.cuda.device_count()}")
    print(f"當前 GPU: {torch.cuda.current_device()}")
    print(f"GPU 名稱: {torch.cuda.get_device_name(0)}")
    print(f"GPU 記憶體: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.2f} GB")
else:
    print("未檢測到 GPU，將使用 CPU")

print("\n" + "="*50 + "\n")

# 2. 指定設備運行 Pipeline
print("=== 2. 指定設備運行 ===\n")

# 方法 1: 使用 device 參數
device = 0 if torch.cuda.is_available() else -1  # 0 表示 GPU 0，-1 表示 CPU
classifier = pipeline("sentiment-analysis", device=device)

print(f"✓ Pipeline 運行在: {'GPU' if device >= 0 else 'CPU'}")

# 測試推理
result = classifier("This is amazing!")
print(f"測試結果: {result}")

print("\n" + "="*50 + "\n")

# 3. 混合精度推理 (FP16)
print("=== 3. 混合精度推理 (加速 2-3 倍) ===\n")

if torch.cuda.is_available():
    import time
    
    # FP32 推理
    model_name = "distilbert-base-uncased-finetuned-sst-2-english"
    model_fp32 = AutoModelForSequenceClassification.from_pretrained(model_name).to("cuda")
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    
    text = "This is a test sentence for performance comparison."
    inputs = tokenizer(text, return_tensors="pt").to("cuda")
    
    # 預熱
    for _ in range(10):
        with torch.no_grad():
            _ = model_fp32(**inputs)
    
    # FP32 推理測試
    start = time.time()
    for _ in range(100):
        with torch.no_grad():
            outputs = model_fp32(**inputs)
    time_fp32 = time.time() - start
    
    # FP16 推理
    model_fp16 = AutoModelForSequenceClassification.from_pretrained(model_name).to("cuda").half()
    inputs_fp16 = {k: v.to("cuda") for k, v in inputs.items()}
    
    # 預熱
    for _ in range(10):
        with torch.no_grad():
            _ = model_fp16(**inputs_fp16)
    
    # FP16 推理測試
    start = time.time()
    for _ in range(100):
        with torch.no_grad():
            outputs = model_fp16(**inputs_fp16)
    time_fp16 = time.time() - start
    
    print(f"FP32 推理時間: {time_fp32:.4f} 秒")
    print(f"FP16 推理時間: {time_fp16:.4f} 秒")
    print(f"加速比: {time_fp32 / time_fp16:.2f}x")
    
    # 記憶體使用比較
    print(f"\nFP32 模型大小: ~{sum(p.numel() * 4 for p in model_fp32.parameters()) / 1024**2:.2f} MB")
    print(f"FP16 模型大小: ~{sum(p.numel() * 2 for p in model_fp16.parameters()) / 1024**2:.2f} MB")
else:
    print("需要 GPU 才能進行混合精度推理")

print("\n" + "="*50 + "\n")

# 4. 模型量化 (8-bit)
print("=== 4. 模型量化 (節省記憶體) ===\n")

try:
    # 需要安裝 bitsandbytes: pip install bitsandbytes
    from transformers import AutoModelForCausalLM
    
    print("載入 8-bit 量化模型（需要 GPU 和 bitsandbytes 庫）...")
    # 注意：這需要較大的模型才能看到明顯效果
    # model_8bit = AutoModelForCausalLM.from_pretrained(
    #     "gpt2",
    #     load_in_8bit=True,
    #     device_map="auto"
    # )
    # print("✓ 8-bit 模型已載入")
    print("（示例代碼已註釋，取消註釋以執行）")
except ImportError:
    print("✗ 需要安裝 bitsandbytes 庫: pip install bitsandbytes")

print("\n" + "="*50 + "\n")

# 5. 批次大小優化
print("=== 5. 動態批次大小優化 ===\n")

def find_optimal_batch_size(model, tokenizer, texts, max_batch_size=32):
    """自動尋找最佳批次大小"""
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = model.to(device)
    
    batch_size = max_batch_size
    while batch_size > 0:
        try:
            # 測試批次處理
            batch_texts = texts[:batch_size]
            inputs = tokenizer(batch_texts, return_tensors="pt", padding=True, truncation=True)
            inputs = {k: v.to(device) for k, v in inputs.items()}
            
            with torch.no_grad():
                _ = model(**inputs)
            
            print(f"✓ 最佳批次大小: {batch_size}")
            return batch_size
        except RuntimeError as e:
            if "out of memory" in str(e):
                batch_size = batch_size // 2
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()
                print(f"  嘗試批次大小: {batch_size}")
            else:
                raise e
    
    return 1

# 測試
test_texts = ["This is a test sentence."] * 100
model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

if torch.cuda.is_available():
    optimal_bs = find_optimal_batch_size(model, tokenizer, test_texts)
else:
    print("在 CPU 上運行，使用預設批次大小 8")

print("\n" + "="*50 + "\n")

# 6. 推理時的記憶體優化技巧
print("=== 6. 記憶體優化技巧總結 ===\n")

optimization_tips = """
✓ 使用 torch.no_grad() 禁用梯度計算
✓ 使用混合精度 (FP16/BF16)
✓ 使用模型量化 (8-bit/4-bit)
✓ 批次處理而非逐一處理
✓ 使用 gradient_checkpointing 訓練大模型
✓ 定期清理 GPU 快取 (torch.cuda.empty_cache())
✓ 使用 device_map="auto" 自動分配設備
✓ 考慮使用 ONNX Runtime 進行部署優化
"""

print(optimization_tips)

print("✅ GPU 配置與優化示範完成！")

## 13. GPU 配置與優化

展示如何配置 GPU 並優化模型性能。

In [ ]:
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification
import torch

# 1. 處理模型載入錯誤
print("=== 1. 安全載入模型 ===\n")

def safe_load_pipeline(task, model_name=None, max_retries=3):
    """安全載入 pipeline，包含錯誤處理和重試機制"""
    for attempt in range(max_retries):
        try:
            if model_name:
                pipe = pipeline(task, model=model_name)
            else:
                pipe = pipeline(task)
            print(f"✓ 成功載入 {task} pipeline")
            return pipe
        except Exception as e:
            print(f"✗ 嘗試 {attempt + 1} 失敗: {str(e)}")
            if attempt == max_retries - 1:
                print(f"✗ 載入失敗，已達最大重試次數")
                return None
    return None

# 示例使用
classifier = safe_load_pipeline("sentiment-analysis")

print("\n" + "="*50 + "\n")

# 2. 處理輸入長度限制
print("=== 2. 處理長文本輸入 ===\n")

model_name = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

long_text = " ".join(["This is a very long text."] * 200)  # 創建超長文本

def safe_inference(text, tokenizer, model, max_length=512):
    """安全執行推理，自動處理長度限制"""
    try:
        # 方法 1: 截斷
        inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=max_length)
        
        # 檢查設備
        device = "cuda" if torch.cuda.is_available() else "cpu"
        model = model.to(device)
        inputs = {k: v.to(device) for k, v in inputs.items()}
        
        # 推理
        with torch.no_grad():
            outputs = model(**inputs)
        
        # 取得預測
        predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
        predicted_class = torch.argmax(predictions, dim=-1).item()
        confidence = predictions[0][predicted_class].item()
        
        return {
            "label": model.config.id2label[predicted_class],
            "confidence": confidence,
            "truncated": len(tokenizer.tokenize(text)) > max_length
        }
    except Exception as e:
        print(f"✗ 推理錯誤: {str(e)}")
        return None

result = safe_inference(long_text, tokenizer, model)
if result:
    print(f"✓ 預測標籤: {result['label']}")
    print(f"✓ 信心度: {result['confidence']:.4f}")
    print(f"✓ 文本被截斷: {result['truncated']}")

print("\n" + "="*50 + "\n")

# 3. 批次處理優化
print("=== 3. 高效批次推理 ===\n")

texts = [
    "I love this product!",
    "This is terrible.",
    "Not bad, could be better.",
    "Amazing experience!",
    "Disappointing quality."
]

# 錯誤方式：逐一處理（慢）
print("逐一處理（慢）:")
import time
start = time.time()
results_slow = []
for text in texts:
    result = classifier(text)
    results_slow.append(result)
time_slow = time.time() - start
print(f"  耗時: {time_slow:.4f} 秒")

# 正確方式：批次處理（快）
print("\n批次處理（快）:")
start = time.time()
results_fast = classifier(texts, batch_size=8)
time_fast = time.time() - start
print(f"  耗時: {time_fast:.4f} 秒")
print(f"  加速比: {time_slow / time_fast:.2f}x")

print("\n" + "="*50 + "\n")

# 4. GPU/CPU 記憶體管理
print("=== 4. 記憶體管理最佳實踐 ===\n")

def clear_memory():
    """清理 GPU/CPU 記憶體"""
    import gc
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        print("✓ GPU 記憶體已清理")
    else:
        print("✓ CPU 記憶體已清理")

# 示例：載入大模型前清理記憶體
clear_memory()

# 檢查 GPU 記憶體使用
if torch.cuda.is_available():
    print(f"\nGPU 記憶體使用:")
    print(f"  已分配: {torch.cuda.memory_allocated() / 1024**2:.2f} MB")
    print(f"  已保留: {torch.cuda.memory_reserved() / 1024**2:.2f} MB")

print("\n" + "="*50 + "\n")

# 5. 設定隨機種子以確保可重現性
print("=== 5. 確保結果可重現 ===\n")

def set_seed(seed=42):
    """設定所有隨機種子"""
    import random
    import numpy as np
    
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False
    
    print(f"✓ 隨機種子已設定為 {seed}")

set_seed(42)

print("\n" + "="*50 + "\n")

# 6. 離線模式（預先下載模型）
print("=== 6. 離線使用模型 ===\n")

print("步驟 1: 預先下載並保存模型")
save_path = "./my_saved_model"

# 下載並保存
model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)
print(f"✓ 模型已保存至 {save_path}")

print("\n步驟 2: 從本地載入（離線模式）")
# 離線載入
model_offline = AutoModelForSequenceClassification.from_pretrained(save_path, local_files_only=True)
tokenizer_offline = AutoTokenizer.from_pretrained(save_path, local_files_only=True)
print(f"✓ 已從本地載入模型")

print("\n✅ 所有最佳實踐示範完成！")

## 12. 錯誤處理與最佳實踐

展示如何處理常見錯誤和實現最佳實踐。

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# 1. 視覺化情感分析結果
texts = [
    "This is amazing!",
    "I don't like this.",
    "It's okay, not great.",
    "Absolutely wonderful!",
    "Terrible experience."
]

# 使用情感分析 pipeline
from transformers import pipeline
sentiment_analyzer = pipeline("sentiment-analysis")
results = sentiment_analyzer(texts)

# 提取標籤和分數
labels = [r['label'] for r in results]
scores = [r['score'] if r['label'] == 'POSITIVE' else -r['score'] for r in results]

# 繪製橫條圖
fig, ax = plt.subplots(figsize=(10, 6))
colors = ['green' if s > 0 else 'red' for s in scores]
bars = ax.barh(range(len(texts)), scores, color=colors, alpha=0.7)
ax.set_yticks(range(len(texts)))
ax.set_yticklabels(texts, fontsize=10)
ax.set_xlabel('Sentiment Score', fontsize=12)
ax.set_title('Sentiment Analysis Results', fontsize=14, fontweight='bold')
ax.axvline(x=0, color='black', linestyle='-', linewidth=0.5)
ax.grid(axis='x', alpha=0.3)

# 添加數值標籤
for i, (bar, score) in enumerate(zip(bars, scores)):
    ax.text(score + 0.02 if score > 0 else score - 0.02, i, f'{abs(score):.3f}', 
            va='center', ha='left' if score > 0 else 'right', fontsize=9)

plt.tight_layout()
plt.show()

print("\n" + "="*50 + "\n")

# 2. 視覺化 NER 結果
from transformers import pipeline

ner = pipeline("ner", model="dslim/bert-base-NER", aggregation_strategy="simple")
text = "Apple Inc. was founded by Steve Jobs in Cupertino, California."
entities = ner(text)

# 創建實體類型的統計
entity_types = {}
for entity in entities:
    entity_type = entity['entity_group']
    entity_types[entity_type] = entity_types.get(entity_type, 0) + 1

# 繪製餅圖
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# 餅圖
colors = plt.cm.Set3(range(len(entity_types)))
ax1.pie(entity_types.values(), labels=entity_types.keys(), autopct='%1.1f%%',
        startangle=90, colors=colors)
ax1.set_title('Entity Type Distribution', fontsize=14, fontweight='bold')

# 條形圖
ax2.bar(entity_types.keys(), entity_types.values(), color=colors, alpha=0.7)
ax2.set_xlabel('Entity Type', fontsize=12)
ax2.set_ylabel('Count', fontsize=12)
ax2.set_title('Entity Count by Type', fontsize=14, fontweight='bold')
ax2.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

# 打印詳細結果
print(f"\n文本: {text}\n")
print("識別的實體：")
for entity in entities:
    print(f"  - {entity['word']}: {entity['entity_group']} (信心度: {entity['score']:.4f})")

## 11. 結果視覺化

使用 matplotlib 和 seaborn 視覺化模型結果。

In [ ]:
import evaluate
import numpy as np

# 載入準確率指標
accuracy_metric = evaluate.load("accuracy")

# 模擬預測結果
predictions = [0, 1, 0, 1, 1]
references = [0, 1, 0, 0, 1]

# 計算準確率
accuracy = accuracy_metric.compute(predictions=predictions, references=references)
print(f"準確率: {accuracy['accuracy']:.4f}")

print("\n" + "="*50 + "\n")

# 使用多個指標
f1_metric = evaluate.load("f1")
precision_metric = evaluate.load("precision")
recall_metric = evaluate.load("recall")

# 計算 F1, Precision, Recall
f1 = f1_metric.compute(predictions=predictions, references=references)
precision = precision_metric.compute(predictions=predictions, references=references)
recall = recall_metric.compute(predictions=predictions, references=references)

print("分類指標：")
print(f"  F1 Score: {f1['f1']:.4f}")
print(f"  Precision: {precision['precision']:.4f}")
print(f"  Recall: {recall['recall']:.4f}")

print("\n" + "="*50 + "\n")

# NLP 專用指標：BLEU (用於翻譯評估)
bleu_metric = evaluate.load("bleu")

predictions_bleu = ["the cat is on the mat"]
references_bleu = [["there is a cat on the mat", "a cat is on the mat"]]

bleu_score = bleu_metric.compute(predictions=predictions_bleu, references=references_bleu)
print(f"BLEU Score: {bleu_score['bleu']:.4f}")

# ROUGE (用於摘要評估)
rouge_metric = evaluate.load("rouge")

predictions_rouge = ["the cat is on the mat"]
references_rouge = ["the cat is sitting on the mat"]

rouge_score = rouge_metric.compute(predictions=predictions_rouge, references=references_rouge)
print(f"\nROUGE Scores:")
for key, value in rouge_score.items():
    print(f"  {key}: {value:.4f}")

## 10. 模型評估與指標

使用 Evaluate 庫計算模型性能指標。

6. 模型推理示例（以 PyTorch 為例）
利用剛剛建立的批次資料傳入模型，並以 softmax 取得預測機率。

In [9]:
# 將批次輸入傳入模型
# Move the input data to the same device as the model
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
pt_batch = {k: v.to(device) for k, v in pt_batch.items()}

pt_outputs = model(**pt_batch)

# 取得 logits，並使用 softmax 計算機率
from torch import nn
pt_predictions = nn.functional.softmax(pt_outputs.logits, dim=-1)
print(pt_predictions)

tensor([[0.0022, 0.0019, 0.0131, 0.2332, 0.7496],
        [0.2084, 0.1826, 0.1969, 0.1755, 0.2365]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)


7. 模型儲存與載入
示範如何將微調後的模型與分詞器儲存至本地（Colab 儲存空間），以及如何從儲存目錄中載入模型。

儲存模型（PyTorch 範例）

In [10]:
pt_save_directory = "./pt_save_pretrained"
tokenizer.save_pretrained(pt_save_directory)
model.save_pretrained(pt_save_directory)


載入模型（PyTorch 範例）

In [11]:
from transformers import AutoModelForSequenceClassification
model = AutoModelForSequenceClassification.from_pretrained(pt_save_directory)

8. 自訂模型建構
使用 AutoConfig 建立自訂配置，並依該配置初始化一個模型。

In [12]:
from transformers import AutoConfig, AutoModel

# 從預訓練模型取得配置，並修改部分參數 (例如：注意力頭數)
my_config = AutoConfig.from_pretrained("distilbert/distilbert-base-uncased", n_heads=12)

# 依自訂配置建立模型（此處建立的是基礎 AutoModel，可根據任務選擇合適的 AutoModelForXXX）
my_model = AutoModel.from_config(my_config)
print(my_model)

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0-5): 6 x TransformerBlock(
        (attention): DistilBertSdpaAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): L

9. 使用 Trainer 進行模型訓練（PyTorch 範例）
以下範例展示如何使用 Hugging Face 提供的 Trainer 來訓練模型。此處以 Rotten Tomatoes 資料集作為示例。

In [15]:
from transformers import TrainingArguments, Trainer, DataCollatorWithPadding
from datasets import load_dataset

# 載入 Rotten Tomatoes 資料集
dataset = load_dataset("rotten_tomatoes")

# 定義分詞函式
def tokenize_dataset(example):
    return tokenizer(example["text"], padding="max_length", truncation=True)

# 對資料集進行分詞處理
dataset = dataset.map(tokenize_dataset, batched=True)

# 建立 DataCollator (將資料整理成統一長度的批次)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# 設定訓練參數
training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=2,
)

# 建立 Trainer 實例
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    data_collator=data_collator,
)

# 執行訓練（如欲測試，可取消下行註解）
trainer.train()


Map:   0%|          | 0/8530 [00:00<?, ? examples/s]

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.


<IPython.core.display.Javascript object>

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

 ··········


wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: m4932981 to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.


Step,Training Loss
500,0.497600
1000,0.416400
1500,0.301000
2000,0.296100


TrainOutput(global_step=2134, training_loss=0.3688146042399241, metrics={'train_runtime': 821.7858, 'train_samples_per_second': 20.76, 'train_steps_per_second': 2.597, 'total_flos': 4488795510435840.0, 'train_loss': 0.3688146042399241, 'epoch': 2.0})